"""investments, snapshots, liabilities

Revision ID: 8914948e1f48
Revises: a74be3cd215d
Create Date: 2026-07-29 20:27:45.369977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8914948e1f48'
down_revision: Union[str, Sequence[str], None] = 'a74be3cd215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('plaid_security_id', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close_price_as_of', sa.Date(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('plaid_security_id', name=op.f('uq_securities_plaid_security_id'))
    )
    op.create_table('account_snapshots',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('available_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_snapshots_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_snapshots')),
    sa.UniqueConstraint('account_id', 'date', name=op.f('uq_account_snapshots_account_id'))
    )
    op.create_table('holdings',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis_cents', sa.BigInteger(), nullable=True),
    sa.Column('institution_value_cents', sa.BigInteger(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_holdings_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_holdings_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings')),
    sa.UniqueConstraint('account_id', 'security_id', name=op.f('uq_holdings_account_id'))
    )
    op.add_column('accounts', sa.Column('apr_percentage', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('next_payment_due_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('minimum_payment_cents', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'minimum_payment_cents')
    op.drop_column('accounts', 'next_payment_due_date')
    op.drop_column('accounts', 'apr_percentage')
    op.drop_table('holdings')
    op.drop_table('account_snapshots')
    op.drop_table('securities')
    # ### end Alembic commands ###
