"""plaid items, accounts, webhook events

Revision ID: 933eca6751e4
Revises: 34adbafe8cd0
Create Date: 2026-07-29 18:20:48.057732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '933eca6751e4'
down_revision: Union[str, Sequence[str], None] = '34adbafe8cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('plaid_item_id', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.Text(), nullable=True),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('sync_cursor', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_items')),
    sa.UniqueConstraint('plaid_item_id', name=op.f('uq_plaid_items_plaid_item_id'))
    )
    op.create_table('plaid_webhook_events',
    sa.Column('webhook_type', sa.Text(), nullable=False),
    sa.Column('webhook_code', sa.Text(), nullable=False),
    sa.Column('plaid_item_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_webhook_events'))
    )
    op.create_table('accounts',
    sa.Column('plaid_item_id', sa.UUID(), nullable=False),
    sa.Column('plaid_account_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('official_name', sa.Text(), nullable=True),
    sa.Column('mask', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('current_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('available_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('credit_limit_cents', sa.BigInteger(), nullable=True),
    sa.Column('balance_as_of', sa.DateTime(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], name=op.f('fk_accounts_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('plaid_account_id', name=op.f('uq_accounts_plaid_account_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('plaid_webhook_events')
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
