"""recurrings

Revision ID: e0b18aff51ab
Revises: 8914948e1f48
Create Date: 2026-07-29 20:41:14.714487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b18aff51ab'
down_revision: Union[str, Sequence[str], None] = '8914948e1f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrings',
    sa.Column('plaid_stream_id', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('merchant_name', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('cadence', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('average_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('last_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source', sa.Text(), server_default='plaid', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_recurrings_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_recurrings_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrings')),
    sa.UniqueConstraint('plaid_stream_id', name=op.f('uq_recurrings_plaid_stream_id'))
    )
    op.add_column('transactions', sa.Column('recurring_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_transactions_recurring_id_recurrings'), 'transactions', 'recurrings', ['recurring_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_recurring_id_recurrings'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'recurring_id')
    op.drop_table('recurrings')
    # ### end Alembic commands ###
