"""transactions, categories, rules

Revision ID: f563eda2ea53
Revises: 933eca6751e4
Create Date: 2026-07-29 18:39:16.505159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f563eda2ea53'
down_revision: Union[str, Sequence[str], None] = '933eca6751e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), server_default='🏷️', nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_income', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exclude_from_budget', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('category_rules',
    sa.Column('merchant_pattern', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Text(), server_default='exact', nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_rules_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_rules'))
    )
    op.create_table('transactions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.Text(), nullable=True),
    sa.Column('plaid_pending_transaction_id', sa.Text(), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('merchant_name', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('pending', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('categorized_by', sa.Text(), server_default='none', nullable=False),
    sa.Column('plaid_category_primary', sa.Text(), nullable=True),
    sa.Column('plaid_category_detailed', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('excluded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('plaid_transaction_id', name=op.f('uq_transactions_plaid_transaction_id'))
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_index('ix_transactions_category_date', 'transactions', ['category_id', 'date'], unique=False)
    op.create_index('ix_transactions_date', 'transactions', ['date'], unique=False)
    op.create_index('ix_transactions_pending_txn_id', 'transactions', ['plaid_pending_transaction_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the Copilot-style default categories.
    from app.services.categorize import DEFAULT_CATEGORIES

    categories_table = sa.table(
        "categories",
        sa.column("name", sa.Text),
        sa.column("emoji", sa.Text),
        sa.column("is_income", sa.Boolean),
        sa.column("exclude_from_budget", sa.Boolean),
        sa.column("sort_order", sa.Integer),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(
        categories_table,
        [
            {
                "name": c["name"],
                "emoji": c["emoji"],
                "is_income": c.get("is_income", False),
                "exclude_from_budget": c.get("exclude_from_budget", False),
                "sort_order": i,
                "is_system": True,
            }
            for i, c in enumerate(DEFAULT_CATEGORIES)
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_pending_txn_id', table_name='transactions')
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.drop_index('ix_transactions_category_date', table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('category_rules')
    op.drop_table('categories')
    # ### end Alembic commands ###
