/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backend/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_backend_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Account */
        patch: operations["patch_account_api_backend_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/backend/accounts/{account_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account History */
        get: operations["get_account_history_api_backend_accounts__account_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Budget */
        put: operations["put_budget_api_backend_budgets_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/budgets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget Summary */
        get: operations["get_budget_summary_api_backend_budgets_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cashflow */
        get: operations["get_cashflow_api_backend_cashflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_backend_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_backend_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_backend_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Patch Category */
        patch: operations["patch_category_api_backend_categories__category_id__patch"];
        trace?: never;
    };
    "/api/backend/category_rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_backend_category_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_backend_category_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/category_rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_backend_category_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_backend_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investments */
        get: operations["get_investments_api_backend_investments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/net-worth/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Net Worth History */
        get: operations["get_net_worth_history_api_backend_net_worth_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/plaid/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange */
        post: operations["exchange_api_backend_plaid_exchange_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/plaid/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_backend_plaid_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/plaid/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_backend_plaid_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/plaid/link_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Token */
        post: operations["link_token_api_backend_plaid_link_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sync */
        post: operations["trigger_sync_api_backend_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_api_backend_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backend/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Transaction */
        patch: operations["patch_transaction_api_backend_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/api/backend/webhooks/plaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plaid Webhook */
        post: operations["plaid_webhook_api_backend_webhooks_plaid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountHistoryPoint */
        AccountHistoryPoint: {
            /** Current Balance Cents */
            current_balance_cents: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** AccountOut */
        AccountOut: {
            /** Available Balance Cents */
            available_balance_cents: number | null;
            /** Balance As Of */
            balance_as_of: string | null;
            /** Credit Limit Cents */
            credit_limit_cents: number | null;
            /** Currency */
            currency: string;
            /** Current Balance Cents */
            current_balance_cents: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Institution Name */
            institution_name: string | null;
            /** Is Hidden */
            is_hidden: boolean;
            /** Mask */
            mask: string | null;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
            /** Subtype */
            subtype: string | null;
            /** Type */
            type: string;
        };
        /** AccountPatch */
        AccountPatch: {
            /** Is Hidden */
            is_hidden: boolean;
        };
        /** AccountsResponse */
        AccountsResponse: {
            /** Accounts */
            accounts: components["schemas"]["AccountOut"][];
        };
        /** AllocationSlice */
        AllocationSlice: {
            /** Label */
            label: string;
            /** Percent */
            percent: number;
            /** Value Cents */
            value_cents: number;
        };
        /** BudgetCategorySummary */
        BudgetCategorySummary: {
            /** Budget Cents */
            budget_cents: number | null;
            category: components["schemas"]["CategoryOut"];
            /** Spent Cents */
            spent_cents: number;
        };
        /** BudgetPut */
        BudgetPut: {
            /** Amount Cents */
            amount_cents: number;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Month
             * Format: date
             */
            month: string;
        };
        /** BudgetSummary */
        BudgetSummary: {
            /** Categories */
            categories: components["schemas"]["BudgetCategorySummary"][];
            /** Income Cents */
            income_cents: number;
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Total Budget Cents */
            total_budget_cents: number;
            /** Total Spent Cents */
            total_spent_cents: number;
        };
        /** CashflowMonth */
        CashflowMonth: {
            /** Expense Cents */
            expense_cents: number;
            /** Income Cents */
            income_cents: number;
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Net Cents */
            net_cents: number;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /**
             * Emoji
             * @default 🏷️
             */
            emoji: string;
            /**
             * Exclude From Budget
             * @default false
             */
            exclude_from_budget: boolean;
            /**
             * Is Income
             * @default false
             */
            is_income: boolean;
            /** Name */
            name: string;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Emoji */
            emoji: string;
            /** Exclude From Budget */
            exclude_from_budget: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Income */
            is_income: boolean;
            /** Is System */
            is_system: boolean;
            /** Name */
            name: string;
            /** Sort Order */
            sort_order: number;
        };
        /** CategoryPatch */
        CategoryPatch: {
            /** Emoji */
            emoji?: string | null;
            /** Exclude From Budget */
            exclude_from_budget?: boolean | null;
            /** Is Income */
            is_income?: boolean | null;
            /** Name */
            name?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** ExchangeRequest */
        ExchangeRequest: {
            /** Institution Id */
            institution_id?: string | null;
            /** Institution Name */
            institution_name?: string | null;
            /** Public Token */
            public_token: string;
        };
        /** ExchangeResponse */
        ExchangeResponse: {
            item: components["schemas"]["PlaidItemOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingOut */
        HoldingOut: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** As Of */
            as_of: string | null;
            /** Close Price */
            close_price: number | null;
            /** Cost Basis Cents */
            cost_basis_cents: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quantity */
            quantity: number;
            /** Security Name */
            security_name: string | null;
            /** Security Type */
            security_type: string | null;
            /** Ticker */
            ticker: string | null;
            /** Value Cents */
            value_cents: number | null;
        };
        /** InvestmentsResponse */
        InvestmentsResponse: {
            /** Allocation */
            allocation: components["schemas"]["AllocationSlice"][];
            /** Holdings */
            holdings: components["schemas"]["HoldingOut"][];
            /** Total Value Cents */
            total_value_cents: number;
        };
        /** LinkTokenRequest */
        LinkTokenRequest: {
            /** Item Id */
            item_id?: string | null;
            /**
             * Kind
             * @default bank
             */
            kind: string;
        };
        /** LinkTokenResponse */
        LinkTokenResponse: {
            /** Link Token */
            link_token: string;
        };
        /** NetWorthPoint */
        NetWorthPoint: {
            /** Assets Cents */
            assets_cents: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Liabilities Cents */
            liabilities_cents: number;
            /** Net Cents */
            net_cents: number;
        };
        /** NetWorthResponse */
        NetWorthResponse: {
            /** Current Assets Cents */
            current_assets_cents: number;
            /** Current Liabilities Cents */
            current_liabilities_cents: number;
            /** Current Net Cents */
            current_net_cents: number;
            /** Series */
            series: components["schemas"]["NetWorthPoint"][];
        };
        /** PlaidItemOut */
        PlaidItemOut: {
            /** Account Count */
            account_count: number;
            /** Error Code */
            error_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Institution Id */
            institution_id: string | null;
            /** Institution Name */
            institution_name: string | null;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Status */
            status: string;
        };
        /** RuleApplyResult */
        RuleApplyResult: {
            /** Retroactively Categorized */
            retroactively_categorized: number;
            rule: components["schemas"]["RuleOut"];
        };
        /** RuleCreate */
        RuleCreate: {
            /**
             * Apply To Existing
             * @default false
             */
            apply_to_existing: boolean;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Match Type
             * @default exact
             */
            match_type: string;
            /** Merchant Pattern */
            merchant_pattern: string;
            /**
             * Priority
             * @default 100
             */
            priority: number;
        };
        /** RuleOut */
        RuleOut: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Match Type */
            match_type: string;
            /** Merchant Pattern */
            merchant_pattern: string;
            /** Priority */
            priority: number;
        };
        /** TransactionOut */
        TransactionOut: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Amount Cents */
            amount_cents: number;
            /** Categorized By */
            categorized_by: string;
            category: components["schemas"]["CategoryOut"] | null;
            /** Currency */
            currency: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Excluded */
            excluded: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Logo Url */
            logo_url: string | null;
            /** Merchant Name */
            merchant_name: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Pending */
            pending: boolean;
        };
        /** TransactionPatch */
        TransactionPatch: {
            /** Category Id */
            category_id?: string | null;
            /** Excluded */
            excluded?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** TransactionsPage */
        TransactionsPage: {
            /** Next Cursor */
            next_cursor: string | null;
            /** Transactions */
            transactions: components["schemas"]["TransactionOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_backend_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_account_api_backend_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_history_api_backend_accounts__account_id__history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountHistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_budget_api_backend_budgets_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_summary_api_backend_budgets_summary_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cashflow_api_backend_cashflow_get: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashflowMonth"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_backend_categories_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_backend_categories_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_backend_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_category_api_backend_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_backend_category_rules_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_backend_category_rules_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleApplyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_backend_category_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_backend_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_investments_api_backend_investments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_net_worth_history_api_backend_net_worth_history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetWorthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_api_backend_plaid_exchange_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_backend_plaid_items_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaidItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_backend_plaid_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_token_api_backend_plaid_link_token_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_backend_sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_backend_transactions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                account_id?: string | null;
                category_id?: string | null;
                search?: string | null;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_transaction_api_backend_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plaid_webhook_api_backend_webhooks_plaid_post: {
        parameters: {
            query?: never;
            header?: {
                "Plaid-Verification"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
